### ISSUE TITLE
Stardoc 0.5.0 complains that Provider is an unhashable type.

### ISSUE THREAD

**Issue by restingbull** [bazelbuild/stardoc#119]
Found a regression in hashing function types, when attempting to upgrade rules_kotlin.

Related: https://github.com/bazelbuild/rules_kotlin/issues/667

# Given:
(see attached zip)
```
LanguageInfo = provider()
OtherLanguageInfo = provider()

a_struct = struct(
    specific_values = {
     LanguageInfo: "value",
     OtherLanguageInfo: "specific value"
    },
)
```

# When:
`bazel build //:provider_hash-docs_4`

# Expect:
```
~/Workspace/stardoc_error bazel build //:provider_hash-docs_4
DEBUG: Rule 'io_bazel_stardoc_4' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "4378e9b6bb2831de7143580594782f538f461180", shallow_since = "1570829166 -0400" and dropping ["tag"]
DEBUG: Repository io_bazel_stardoc_4 instantiated at:
  /tmp/stardoc_error/WORKSPACE:18:15: in <toplevel>
Repository rule git_repository defined at:
 /tmp/_bazel/91a6e79d1af869e580bb966fd23d00e2/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //:provider_hash-docs_4 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:provider_hash-docs_4 up-to-date:
  bazel-bin/provider_hash_4.md
INFO: Elapsed time: 0.072s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
# Actual:
```
~/Workspace/stardoc_error bazel build //:provider_hash-docs_5
DEBUG: Rule 'io_bazel_stardoc_4' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "4378e9b6bb2831de7143580594782f538f461180", shallow_since = "1570829166 -0400" and dropping ["tag"]
DEBUG: Repository io_bazel_stardoc_4 instantiated at:
  /stardoc_error/WORKSPACE:18:15: in <toplevel>
Repository rule git_repository defined at:
 /tmp/_bazel/91a6e79d1af869e580bb966fd23d00e2/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //:provider_hash-docs_5 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: //stardoc_error/BUILD.bazel:4:10: Generating proto for Starlark doc for provider_hash-docs_5 failed: (Exit 1): stardoc failed: error executing command bazel-out/host/bin/external/io_bazel_stardoc_5/stardoc/stardoc '--input=//:provider_hash.bzl' '--workspace_name=__main__' '--dep_roots=.' '--dep_roots=external/__main__' ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: Starlark evaluation error
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:428)
        at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:260)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:163)
Caused by: Traceback (most recent call last):
        File "./provider_hash.bzl", line 6, column 18, in <toplevel>
                LanguageInfo: "value",
Error: unhashable type: 'Provider'
        at net.starlark.java.eval.Starlark.errorf(Starlark.java:663)
        at net.starlark.java.eval.StarlarkValue.checkHashable(StarlarkValue.java:99)
        at net.starlark.java.eval.Starlark.checkHashable(Starlark.java:152)
        at net.starlark.java.eval.Dict.putEntry(Dict.java:489)
        at net.starlark.java.eval.Eval.evalDict(Eval.java:558)
        at net.starlark.java.eval.Eval.eval(Eval.java:486)
        at net.starlark.java.eval.Eval.evalCall(Eval.java:632)
        at net.starlark.java.eval.Eval.eval(Eval.java:490)
        at net.starlark.java.eval.Eval.execAssignment(Eval.java:109)
        at net.starlark.java.eval.Eval.exec(Eval.java:269)
        at net.starlark.java.eval.Eval.execStatements(Eval.java:82)
        at net.starlark.java.eval.Eval.execFunctionBody(Eval.java:66)
        at net.starlark.java.eval.StarlarkFunction.fastcall(StarlarkFunction.java:191)
        at net.starlark.java.eval.Starlark.fastcall(Starlark.java:617)
        at net.starlark.java.eval.Starlark.execFileProgram(Starlark.java:892)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:425)
        ... 2 more
Stardoc documentation generation failed: Starlark evaluation error
Target //:provider_hash-docs_5 failed to build
Use --verbose_failures to see the command lines of failed bu
[repro_case.zip](https://github.com/bazelbuild/stardoc/files/7954466/repro_case.zip)
ild steps.
INFO: Elapsed time: 0.350s, Critical Path: 0.27s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by tetromino** [comment]
Looks like we need to override `isImmutable` in https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/skydoc/fakebuildapi/FakeProviderApi.java, and once that's done, regenerate Stardoc's bundled jars.

And I'm quite surprised that the example doesn't crash Stardoc 0.4 - it happened to work by accident :)
