### ISSUE TITLE
Update jar

### ISSUE THREAD

**Issue by keith** [bazelbuild/stardoc#63]
It seems like there have been some error handling improvements upstream. With stardoc currently:

```
% bazel-out/host/bin/external/io_bazel_stardoc/stardoc/stardoc '--input=//bazel:module.bzl' '--workspace_name=lyftios' '--dep_roots=.' '--dep_roots=external/lyftios' '--output=bazel-out/darwin-fastbuild/bin/bazel/module-docs.raw'
Stardoc documentation generation failed: Starlark evaluation error
```

With the upstream jar:

```
% java -jar /private/var/tmp/_bazel_ksmiley/cdf42e3ebdb7335cbe8a7a6c07c7aed8/execroot/io_bazel/bazel-out/darwin-fastbuild/bin/src/main/java/com/google/devtools/build/skydoc/skydoc_deploy.jar '--input=//bazel:module.bzl' '--workspace_name=lyftios' '--dep_roots=.' '--dep_roots=external/lyftios' '--output=bazel-out/darwin-fastbuild/bin/bazel/module-docs.raw'
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: File external/build_bazel_rules_swift/swift/internal/swift_grpc_library.bzl imported '@rules_proto//proto:defs.bzl', yet external/rules_proto/proto/defs.bzl was not found, even at roots [., external/lyftios].
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:467)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:457)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:457)
        at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:325)
        at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:228)
Caused by: java.nio.file.NoSuchFileException: external/rules_proto/proto/defs.bzl
        at com.google.devtools.build.skydoc.SkydocMain.getInputSource(SkydocMain.java:501)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:443)
        at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:457)
        ... 4 more
Stardoc documentation generation failed: File external/build_bazel_rules_swift/swift/internal/swift_grpc_library.bzl imported '@rules_proto//proto:defs.bzl', yet external/rules_proto/proto/defs.bzl was not found, even at roots [., external/lyftios].
```

Is there a process for updating this?

**Comment by larsrc-google** [comment]
@keith Did #65 fix your issue?

**Comment by keith** [comment]
yep, thanks!
